### ISSUE TITLE
ValueError: test_size=8 should be either positive and smaller than the number of samples 0 or a float in the (0, 1) range

### ISSUE THREAD

**Issue by yanmingqiang** [RElbers/ada-conv-pytorch#1]
Hello, I am glad to see your article, I was very inspired, but when I run the code you provided, it appeared
ValueError: test_size=8 should be either positive and smaller than the number of samples 0 or a float in the (0, 1) range

Can you help me solve this problem?

**Comment by RElbers** [comment]
Hi. Looks like I pushed code with the data folder already filled in. In the `add_argparse_args` function in `/lib/lightning/datamodule.py` set the default values for content and style to the correct path for you. Or you can run the script with the directories as command line arguments;  `python .\train.py --content=<path/to/content-images> --style=<path/to/style-images>`

The content images are from the train2017 set of MSCOCO (https://cocodataset.org) and the style images are from the WikiArt dataset (https://www.kaggle.com/c/painter-by-numbers). 

BTW I didnt write the paper. I just found it interesting and am trying to implement it ;)
