### ISSUE TITLE
Bias before pointwise conv

### ISSUE THREAD

**Issue by ariG23498** [RElbers/ada-conv-pytorch#2]
https://github.com/RElbers/ada-conv-pytorch/blob/bb3bab5820b2fb668e9a590269d0cb827437fdfd/lib/nn/adaconv/adaconv.py#L44

In the paper the bias is added after the pointwise cov. Is there a reason why we do it before here?

**Comment by RElbers** [comment]
I think you are correct and that's a bug in the code. I have been refactoring the code as well. I'll push the new code with this bug fixed later today.

**Comment by ariG23498** [comment]
I think this has been sorted in the latest commit. Feel free to close this!
